name: flutter_clean_architecture_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  dio: ^5.7.0
  floor: 1.4.2
  flutter:
    sdk: flutter
  http: 1.1.0
  sqflite: 2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/